### ISSUE TITLE
Python 3.10.0a2 breakage

### ISSUE THREAD

**Issue by hroncok** [fedora-python/marshalparser#10]
See https://src.fedoraproject.org/rpms/python3.10/pull-request/8#comment-59965

```
+ marshalparser /usr/lib64/python3.10/email/mime/__pycache__/audio.cpython-310.opt-1.pyc
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/marshalparser/marshalparser.py", line 205, in read_object
    self.record_object_result(result)
UnboundLocalError: local variable 'result' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/marshalparser", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/marshalparser/marshalparser.py", line 373, in main
    parser.parse()
  File "/usr/lib/python3.9/site-packages/marshalparser/marshalparser.py", line 57, in parse
    self.read_object()
  File "/usr/lib/python3.9/site-packages/marshalparser/marshalparser.py", line 207, in read_object
    raise RuntimeError(
RuntimeError: Error: type [TYPE_FLOAT] is recognized but result is not present
```

**Comment by hroncok** [comment]
Fixed in version 0.2.2 via 5eedd2ffc1a53e456bf4553862e2409a7caf8584
